### ISSUE TITLE
Pinned Tabs

### ISSUE THREAD

**Issue by nir-zilberman** [matthias-vogt/tab-limiter#2]
Pinned tabs are not being counted/limited.

**Comment by juni-vogt** [comment]
Thanks I'll look into this, should be an easy fix

**Comment by nir-zilberman** [comment]
@matthias-vogt, I understand that this issue was fixed in the latest release, thanks!

**Comment by juni-vogt** [comment]
Yes, it's an option now lol. You're welcome!
