### ISSUE TITLE
Incognito windows/tabs are not included

### ISSUE THREAD

**Issue by johnaau** [matthias-vogt/tab-limiter#3]
This might be a hard one but when the limit is reached the user can open incognito windows and tabs which are not counted.

**Comment by juni-vogt** [comment]
Sorry for the late reply, thank you for the issue! :)
This actually works for me. You just have to allow the extension in incognito mode at chrome://extensions. Also note that maybe your window limit is smaller than your overall tab limit, so what you see might be intended behaviour.
