### ISSUE TITLE
Add an option to count only HTTP/HTTPS tabs

### ISSUE THREAD

**Issue by nir-zilberman** [matthias-vogt/tab-limiter#6]
Could you please add an option to count only HTTP/HTTPS tabs?
(meaning tabs that use these URL Schemes: `http://`, `https://`)

If this option is enabled, then tabs that use other URL schemes will not be counted
(for example, tabs that use these URL Schemes: `chrome://`, `chrome-extension://`, `file://`, `filesystem://`)

**Comment by juni-vogt** [comment]
Thanks for your feature request. I would like to avoid adding more options to not make the extension more cluttered. What is your use case for this?

**Comment by nir-zilberman** [comment]
@matthias-vogt the use case is to allow the extension to only limit the number of open tabs of real web pages, without blocking/limiting other tabs, such as settings

**Comment by juni-vogt** [comment]
Thanks again for the suggestion. However, I see some problems with the feature.

- I think the feature would be difficult to implement properly. For example, consider a user opening settings while the tab limit is reached. If they navigated to an actual website in this tab, it would have to be prevented.
- Moreover, if the feature was implemented, the extension would not create a popup and prevent opening a new tab (i.e. opening `chrome://newtab`) while the tab limit is reached. But I like that behaviour and I think it's better UX than closing the tab after having entered the url already.

For these reasons, I would not implement this feature.
